### ISSUE TITLE
nothing happens after run the bot

### ISSUE THREAD

**Issue by johngalt13** [Mosuswalks/snkrs-bot#10]
Hi, thanks for your efforts. But it looks like it not working.
 I'm trying to start "node bot.js" in Windows and it never open Chromium. headless - false. Just nothing in the console
at least it should able to start Chromium. 
I was able to start a different code, but in your code, I like that it trying login first.

**Comment by leonxiaopeng** [comment]
@johngalt13  i get the same problem . it not working at all. could you please tell me another way to do this?

**Comment by johngalt13** [comment]
> @johngalt13 i get the same problem . it not working at all. could you please tell me another way to do this?

Hi, you can try to use this - https://github.com/tylerburleigh/nike-buy-bot but it not working when need to click "save" on the CC page.  so you need to select a different selector for it and everything will work fine.
